### ISSUE TITLE
Title: Header disappears when scrolling over parallax sticky background

### ISSUE THREAD

**Issue by alm6666** [dgtalForest/react_restaurant_landing#4]
## Description
When scrolling the page, the header becomes hidden as it passes over the parallax sticky background section. This creates a poor user experience and makes navigation difficult.

## Steps to Reproduce
1. Open the home page
2. Scroll down slowly until you reach the parallax section with a sticky background
3. Continue scrolling through this section
4. Observe the header as it passes over the parallax background

## Expected Behavior
The header should remain visible and accessible at all times, even when scrolling over the parallax sticky background section.

## Actual Behavior
The header disappears or becomes hidden behind the parallax sticky background as the user scrolls through this section.

## Screenshots / Video
[If possible, add a screenshot or short video demonstrating the issue]

## Environment
- Browser: [e.g., Chrome 91, Firefox 89]
- OS: [e.g., Windows 10, macOS Big Sur]
- Screen resolution: [e.g., 1920x1080]

## Additional Context
This issue seems to be related to the z-index stacking of the header and parallax elements. The parallax section may have a higher z-index than the header, causing this overlap.

## Possible Solution
Consider adjusting the z-index values to ensure the header always appears on top of other page elements, including the parallax background.

**Comment by Mordiacci** [comment]
Thank you for reporting this issue. We've identified the problem with the header disappearing over the parallax sticky background, and I'm glad to inform you that it will be fixed soon.

Our development team has prioritized this bug and is currently working on a solution. I expect to have a fix implemented in our next update.

The fix will involve adjusting the z-index values to ensure the header remains visible at all times, even when scrolling over the parallax section.

I'm closing this issue now, but please don't hesitate to reopen it if you notice the problem persisting after our next update.

Thank you again for your contribution to improving our project!

**Comment by adrilSoft** [comment]
Thank you for reporting this issue. We've identified the problem with the header disappearing over the parallax sticky background, and I'm glad to inform you that it will be fixed soon.

Our development team has prioritized this bug and is currently working on a solution. We expect to have a fix implemented in our next update.

The fix will involve adjusting the z-index values to ensure the header remains visible at all times, even when scrolling over the parallax section.

I'm closing this issue now, but please don't hesitate to reopen it if you notice the problem persisting after our next update.

Thank you again for your contribution to improving our project!

**Comment by adrilSoft** [comment]
Closing the issue

**Comment by dgtalForest** [comment]
Thank you for reporting this issue. We've identified the problem with the header disappearing over the parallax sticky background, and I'm glad to inform you that it will be fixed soon.

Our development team has prioritized this bug and is currently working on a solution. We expect to have a fix implemented in our next update.

The fix will involve adjusting the z-index values to ensure the header remains visible at all times, even when scrolling over the parallax section.

I'm closing this issue now, but please don't hesitate to reopen it if you notice the problem persisting after our next update.

Thank you again for your contribution to improving our project!

**Comment by alm6666** [comment]
Not fixed yet,  let me work on this issue.
